### ISSUE TITLE
希望能支持 AES解密

### ISSUE THREAD

**Issue by Nchujx** [Vnzen/Vnzen_m3u8_Threads_Download#1]

**Comment by anwenzen** [comment]
可以提供一下你的URL吗，要不然我都不知道去哪找一个例子来测试

**Comment by Nchujx** [comment]
类似虎课网的就是，我觉得我们可以讨论下，加我qq吧，1203083157

**Comment by Nchujx** [comment]
> 可以提供一下你的URL吗，要不然我都不知道去哪找一个例子来测试
类似虎课网的就是，我觉得我们可以讨论下，加我qq吧，1203083157
